# Generated by Django 4.2.3 on 2023-09-30 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
