# Generated by Django 4.2.3 on 2023-09-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='summary',
            field=models.CharField(max_length=200),
        ),
    ]
