# Generated by Django 4.2.4 on 2023-10-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_alter_summary_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelhiGeneration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('GENCO', models.CharField(max_length=200)),
                ('schedule', models.IntegerField()),
                ('actual', models.IntegerField()),
                ('UI', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DiscomDrawl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discom', models.IntegerField()),
                ('schedule', models.IntegerField()),
                ('drawl', models.IntegerField()),
                ('OD', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StateDrawl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=200)),
                ('schedule', models.IntegerField()),
                ('drawl', models.IntegerField()),
                ('OD', models.IntegerField()),
                ('load', models.IntegerField()),
            ],
        ),
    ]
