# Generated by Django 4.2.4 on 2023-10-01 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0005_delhigeneration_discomdrawl_statedrawl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statedrawl',
            name='load',
        ),
    ]
