# Generated by Django 4.2.4 on 2023-10-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0006_remove_statedrawl_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discomdrawl',
            name='discom',
            field=models.CharField(max_length=200),
        ),
    ]
